# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48709a2d5dae8529760fdb9f7850991041db45ae8340729cc5a6e04e182acaa7f2cd3c9aea92546a32b80b21a12946b6f4d63126c635aa8126daf09453afa082

test:
  secret_key_base: 619f21e609f1e1bedb97b34c2ec3cde605d71b50cc7b41d6c27c9c32751d708ac6d3cc642ca14988f82ee2c3d17a36f26bf75e693e56c56b946db507fe1c2dbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
